### ISSUE TITLE
[RFE] Need to write a deployable app that allows Users to register and get given a username

### ISSUE THREAD

**Issue by utherp0** [utherp0/workshop4#36]
An online registrations service that hands out the userx users - would be nice if:

1: We can change the password in the htpasswd secret so each user can have their own password - if we do we'd probably need to add a feature to update or reset the password in the situation a user forgets as well

2: The App should perform an SCC controlled update of the User object to add the User name metadata to the user - in order to do this the user must be logged in once, so the process would be register, log on for them, change the label, logoff.

**Comment by browningjp** [comment]
Could even do away with the userX format - have people choose their own usernames

**Comment by browningjp** [comment]
resolved using username-distribution app + workshopper app
