### ISSUE TITLE
[RFE] Make the course structure more dynamic

### ISSUE THREAD

**Issue by utherp0** [utherp0/workshop4#44]
Rather than having basic and advanced courses make it a single course with a highly configurable selection method for chapters, i.e. a shopping list

**Comment by browningjp** [comment]
Let's chat next week about this - I've finally got my Dockerfile working that builds and hosts the documentation for you all on the cluster

https://github.com/browningjp/devexDockerfile

Would be good to make it as automated as possible, especially if others want to start running these workshops

**Comment by utherp0** [comment]
There is a new branch called 'dynamic' where I'll be doing some tests to see how easy it is to scaffold a build and modify the index.asciidoc
