### ISSUE TITLE
Add rocket chat to cluster

### ISSUE THREAD

**Issue by BaxxiJ** [utherp0/workshop4#48]
Cluster wide chat for virtual workshops

**Comment by utherp0** [comment]
Got the Rocketchat stuff enabled, just need to write it up and automate it a bit

Basically:

1: Create a chat project
2: Add the operator to *only* this project
3: When the operator has loaded create a new instance of Rocketchat from the Operator Menu
4: Enable a route for the quickstart service
5: Click on the route - first time will walk you through creating an admin and the chat channels - I create an additional #support channel

**Comment by utherp0** [comment]
Added full instructions in the README on creating the Rocketchat and Etherpad
