### ISSUE TITLE
git clone correction 

### ISSUE THREAD

**Issue by ffirg** [utherp0/workshop4#74]
Under chapter - Application Deployment Configurations and DevOps Approaches

Goto http://basic-docs.apps.cluster-devex1-4789.devex1-4789.example.opentlc.com/#creating-the-applications

change:
git clone https://github.com/utherp0/workshop4.git
cd attendee/myholiday

to:
git clone https://github.com/utherp0/workshop4.git
cd workshop4/attendee/myholiday

**Comment by utherp0** [comment]
Fixed
